# Site settings
title:          Siru's Silly Space
description:    "Safe space for Sirutonin's stupid stories and spiels."
baseurl:        ""
url:            "https://siruthesiru.github.io"

# Google Analytics

# Author
author:
  name:         Sirutonin
  url:          https://siruthesiru.github.io
  email:        sirutonin@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages


# Defaults

defaults:
  -
    values:
      layout: "post"
      comments: false

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:
  shortname: sirutonin

timezone: Asia/Manila