# config.yml

backend:
  name: git-gateway
  repo: siruthesiru/siruthesiru.github.io
  branch: gungnir # Branch to update (optional; defaults to master)

api_root: https://api.github.com

base_url: https://api.netlify.com
auth_endpoint: auth

site_url: siruthesiru.github.io

media_folder: 'img/in-post/2022'
publish_mode: editorial_workflow

collections:
  - name: 'post'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_posts'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    view_filters:
      - label: Drafts
        field: draft
        pattern: true

    view_groups:
      - label: Year
        field: date
        pattern: \d{4}

    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }